### ISSUE TITLE
Quarkus container fails to start

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/testing#3]
## Issue

The quarkus container fails to start 
```
Setting Active Processor Count to 6
Calculating JVM memory based on 3315800K available memory
For more information on this calculation, see https://paketo.io/docs/reference/java-reference/#memory-calculator
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx2732490K -XX:MaxMetaspaceSize=71309K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 3315800K, Thread Count: 250, Loaded Class Count: 10176, Headroom: 0%)
Enabling Java Native Memory Tracking
Adding 124 container CA certificates to JVM truststore
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -XX:+ExitOnOutOfMemoryError -XX:ActiveProcessorCount=6 -XX:MaxDirectMemorySize=10M -Xmx2732490K -XX:MaxMetaspaceSize=71309K -XX:ReservedCodeCacheSize=240M -Xss1M -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics
Exception in thread "main" java.nio.file.NoSuchFileException: /workspace/quarkus/quarkus-application.dat
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
        at java.base/java.nio.file.Files.newInputStream(Unknown Source)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:52)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)

Native Memory Tracking:

Total: reserved=3373179167, committed=159596831
       malloc: 16277791 #6390
       mmap:   reserved=3356901376, committed=143319040

-                 Java Heap (reserved=2799697920, committed=85983232)
                            (mmap: reserved=2799697920, committed=85983232) 
 
-                     Class (reserved=67206812, committed=229020)
                            (classes #967)
                            (  instance classes #843, array classes #124)
                            (malloc=97948 #1149) 
                            (mmap: reserved=67108864, committed=131072) 
                            (  Metadata:   )
                            (    reserved=67108864, committed=655360)
                            (    used=615544)
                            (    waste=39816 =6.08%)
                            (  Class space:)
                            (    reserved=67108864, committed=131072)
                            (    used=52848)
                            (    waste=78224 =59.68%)
...
```

when we execute this command using `git clone https://github.com/quarkusio/quarkus-quickstarts.git`:
```
REGISTRY_HOST="kind-registry.local:5000"
pack build ${REGISTRY_HOST}/quarkus-hello \
     -e BP_NATIVE_IMAGE="false" \
     -e BP_MAVEN_BUILT_ARTIFACT="target/quarkus-app/lib/ target/quarkus-app/*.jar" \
     -e BP_MAVEN_BUILD_ARGUMENTS="package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar" \
     --path ./quarkus-quickstarts/getting-started
```

Do you know why ? @BarDweller @matejvasek

**Comment by cmoulliard** [comment]
I fixed the problem partially 96a9a91dd705741741ed8fc243f71a4cd1602bc5
